[build]
  command = "npm run build"
  publish = ".next"

[functions]
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"

[functions."___netlify-server-handler"]
  timeout = 26

[[plugins]]
  package = "@netlify/plugin-nextjs"
